projet Projet PDB 2526
charger Charger
sauver Sauver
créer Créez...
inst.existePas Cette installation n'existe pas
inst.id Entrez l'id de l'installation

choix.quitter.sauver Quitter et Sauver
choix.quitter.pas.sauver Quitter sans sauver
choix.quitter Quitter
choix.annuler Revenir à l'application

end.confirm.titre Confirmation de la fermeture
end.confirm.info Vous êtes sur le point de quitter l'application
end.confirm.question Voulez-vous quitter l'application ?

msg.save.before.action Vous devez sauver les modifications avant de déplacer une ligne de groupe!
choix.sauver.deplacer Sauver et déplacer
choix.annule.deplacer annule le déplacement

installation Installation
app Appareil


ctx.addPiece Ajoute une pièce
ctx.delPiece Supprime une pièce

app.codes Codes autorisés
app.prise Prise
app.interrupteur Interrupteur
app.lampe Lampe
app.appareillage Appareillage
app.telerupteur Télérupteur
app.televariateur Télévariateur
app.transformateur Transformateur
app.bouton Bouton

conf.save Voulez-vous sauvez les modifications ?
err.save Erreur lors de la sauvegarde
err.noInstall Pas d'installation chargée
err.update La mise à jour n'a pas fonctionné
err.nbr Il faut entrer un nombre!
err.appareil.code.existe.pas Le code {0} n''existe pas pour l''objet {1}


bt.load Charger une Installation
bt.update Modifie l'installation
bt.save Sauve l'installation

bt.element Eléments
bt.associe.piece Associe à une pièce
bt.schema Schéma étage

action.ok  Valider
action.add  Ajout
action.maj  Mise à Jour
action.del  Supprimer
action.quitter  Quitter
action.save Sauver
action.check Vérification

action.annuler  Annuler
action.charger  Charger
