-- Vide les tables
DELETE FROM TLOCALISATION;
DELETE FROM TELEMENT;
DELETE FROM TPLAN;
DELETE FROM TPIECE;
DELETE FROM TTYPE_PIECE;


ALTER TABLE TPLAN ALTER ID_PLA restart with 1;
ALTER TABLE TPIECE ALTER NUM_PIE restart with 1;

-- Encode les données dans la base de données de test
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SALON','Salon',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('LIVING','Living',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SDB','Salle de bain',true);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SAM','Salle à manger',false);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('SALON','Salon principal', 0, 'SALON', 3);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('Salle à manger','Salle à manger principal', 0, 'SAM', 3);

INSERT INTO TPLAN (NOM_PLA, FICHIER_PLA, ETAGE_PLA, FKINSTALLATION_PLA)
VALUES ('Rez-de-chaussée', 'rez.png', 0.0, 3);

INSERT INTO TPLAN (NOM_PLA, FICHIER_PLA, ETAGE_PLA, FKINSTALLATION_PLA)
VALUES ('Etage', 'etage.png', 1.0, 3);

INSERT INTO TELEMENT (ID_ELE, FKAPPAREIL_ELE, QT_ELE, CODE_ELE, INFO_ELE, ORDRE_ELE, FKINSTALLATION_ELE)
VALUES (1, 'PIP2', 1, 'E001', 'Element test 1', 1, 3);

INSERT INTO TELEMENT (ID_ELE, FKAPPAREIL_ELE, QT_ELE, CODE_ELE, INFO_ELE, ORDRE_ELE, FKINSTALLATION_ELE)
VALUES (2, 'PIP2', 1, 'E002', 'Element test 2', 2, 3);

INSERT INTO TELEMENT (ID_ELE, FKAPPAREIL_ELE, QT_ELE, CODE_ELE, INFO_ELE, ORDRE_ELE, FKINSTALLATION_ELE)
VALUES (3, 'PIP2', 1, 'E003', 'Element test 3', 3, 3);